### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by marzsv** [hashdog/scrapfy-atom#1]
I'm using Atom 1.9.9 on OSX and I already installed this package and when I press `ctrl + alt + s` nothing happens, I already tried executing the command directly and nothing happens too.

**Comment by chebyte** [comment]
Now I'm supporting this Wish on Beerpay https://beerpay.io/hashdog/scrapfy-atom/wishes/57c987b758bb2e287854c782

🍻 Cheers!

**Comment by chebyte** [comment]
Wish granted successfully on Beerpay! https://beerpay.io/hashdog/scrapfy-atom/wishes/57c987b758bb2e287854c782
This issue will be closed.

🍻 Cheers!
